image: maven:3-openjdk-17

build-test:
  stage: build
  tags:
    - groupe5
  script:
    - chmod +x ./settings.sh

    - ./settings.sh

    - mvn clean jacoco:prepare-agent test jacoco:report install sonar:sonar deploy
